#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/advertisement
#    username: "sa"
#    password: "0430"
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true


aes256:
  alg : "AES/CBC/PKCS5Padding"
  key : "testqpfienduekdjsudkendjsuajwn2k"